### PR TITLE
feat: add basic cli with an empty init command, json-schemas for systems and variants, and type compilation

### PR DESCRIPTION
**Pull request by patrickocoffeyo**
For this: https://github.com/emulsify-ds/emulsify-cli/projects/1#card-54362798

To test:
 - [x] Clone this repository.
 - [x] Navigate into the repository root: `cd emulsify-cli`.
 - [x] Make sure you are using the correct version of node: `nvm use`.
 - [x] Run `npm i`.
 - [x] In a separate terminal tab or window, run `npm run watch`.
 - [x] In this repository root, run `npm link`.
 - [x] In a random directory, run `emulsify init cornflake`.
 - [x] Note that you receive an error message: `Unable to find a directory to put Emulsify in. Please specify a directory using the "path" argument: emulsify init myTheme ./themes`
 - [x] Run `emulsify init cornflake ./themes` in a random directory.
 - [x] Note that you receive an error message: `Unable to find an Emulsify starter for your project. Please specify one using the --starter flag: emulsify init myTheme --starter https://github.com/emulsify-ds/emulsify-drupal.git`
 - [x] Run `emulsify init cornflake ./themes --starter https://github.com/emulsify-ds/emulsify-drupal.git`
 - [x] Note that you see a success message.
 - [x] Note that you see a `themes/cornflake` directory that contains the Emulsify Drupal starter at 2.x.
 - [x] Navigate to a Drupal codebase
 - [x] Run `emulsify init cornflake`.
 - [x] Note that the CLI identifies that you are in a Drupal project, and uses that to determine the destination folder, as well as the starter that should be used.
 - [x] Note that a theme is created in `./themes/cornflake`.
 - [x] Run `emulsify init cornflake`
 - [x] Note that you get an error message: `The intended target is already occupied: /home/uname/Projects/fourkitchens/test-em/themes/cornflake`

### CODE REVIEW

**Comment by ModulesUnraveled** [comment]
For Drupal projects, the theme should get created in `/themes/custom/<theme-name>`

**Comment by evanmwillhite** [comment]
I got so far as the Drupal step. To install Drupal, I ran `composer create-project drupal/recommended-project DIR_NAME` and changed into that directory. I ran `emulsify init cornflake` in both the root and `web` directory got the message `Unable to find a directory to put Emulsify in. Please specify a directory using the "path" argument: emulsify init myTheme ./themes`.

**Review by evanmwillhite — APPROVED** [review]
Functional steps check out. One thing though is that we should probably remove the `.git` directory inside the theme if it's in a Drupal project?

**Comment by patrickocoffeyo** [comment]
I am merging this in order to unblock myself, but I will follow up with another PR to resolve any code review comments from @nJim. Thank you for your fn review @evanmwillhite and @ModulesUnraveled!

**Review by nJim — APPROVED** [review]
I really like a lot of these decisions. The use of system/variant is a good pattern and the fact that everything is typed and tested makes me feel extra confident in the code. Completed code review and all looks great.

**Pull request merged**
