### PR TITLE
Release with fix for Component command

### PR DESCRIPTION
**Pull request by mikeethedude**
PR for release to fix component command

### CODE REVIEW

**Comment by mikeethedude** [comment]
@callinmullaney Can you double check I'm doing this right?

**Comment by mikeethedude** [comment]
@callinmullaney Good call on the version bump! Totally missed that.

**Review by callinmullaney — APPROVED** [review]
@mikeethedude :shipit:

**Comment by mikeethedude** [comment]
I had to go back and re-sign a commit but now I think we are good.

**Pull request merged**
