### PR TITLE
build: updating dependencies and linting

### PR DESCRIPTION
**Pull request by ModulesUnraveled**
**Summary**

This PR fixes/implements the following:

- Updates dependencies to satisfy Dependabot tickets, etc.
- Lints all the things

**How to review this PR**
- [ ] Pull this branch down, run `npm build` and `npm link`
- [ ] Run `npm run test` and verify no failing test
- [ ] Run `npm run lint` and verify there are no linting issues
- [ ] Create a new Drupal project somewhere. I used `composer create-project drupal/recommended-project drupal-folder`
- [ ] Go into that folder and run `npm link @emulsify/cli`
- [ ] Run `emulsify init "Theme Name"` and verify a theme is initialized

### CODE REVIEW

**Review by patrickocoffeyo — APPROVED** [review]

**Comment by patrickocoffeyo** [comment]
LGTM, nothing functional is changing here 👍

**Comment by ModulesUnraveled** [comment]
@patrickocoffeyo oh shoot! I meant to ask about the new linting config. It removed some parentheses that I found helpful. I wanted your opinion on if we should override the new setting

**Comment by patrickocoffeyo** [comment]
@ModulesUnraveled as in this diff [here](https://github.com/emulsify-ds/emulsify-cli/pull/94/files#diff-40857dba65143f816b2942587c62a38b6cde00b76625f6e746b73362cd9ed02cL41)? I think it's fine either way, it's a matter of stylistic preference and does not alter the way the code functions.

**Comment by ModulesUnraveled** [comment]
Yeah, that's what I was referring to. And I understand it's a stylistic preference, but it seemed clearer to me the polls way. Oh well...

**Comment by patrickocoffeyo** [comment]
Yeah, so you can adjust that rule and add 'em back if you prefer, either way is totally fine 👍

**Pull request merged**
